### ISSUE TITLE
NOT VALID: Error while testing raw metadata against schema

### ISSUE THREAD

**Issue by guifftc** [blobtoolkit/specification#1]
Dear developers,

trying to validate my BlobDir obtained from blobtools create + add --hits --cov --busco I've got this error:
NOT VALID: Error while testing raw metadata against schema
data must contain ['accession', 'prefix'] properties

So I compared the example BlobDir and mine and found that mine was missing these "properties". I added these lines with the same id string and run validate.py again:

NOT VALID: Error while testing raw metadata against schema
data must contain ['taxid', 'name'] properties

I added these lines and it was validated.

My questions are: did I run blobtools create or add without some key parameters? I run them as such (transcripts is the generic name for the loop variable I'm using since I work with multiple species & BlobDir path is simplified, I always use full path on a macOS X):

./blobtools create --fasta transcripts.fasta --taxid 1246790 --taxdump ../taxdump /BlobDir_folder

./blobtools add --hits transcripts_dmnd_blastx.out --taxdump ../taxdump /BlobDir_folder
Loading parsed taxdump
bestsumorder

./blobtools add --cov transcripts_minimap2.bam=transcripts --threads 4 /BlobDir_folder
Loading mapping data from /transcripts_minimap2.bam as transcripts
 99%|███████████████████████████████████████████████████████████████████▏| 38.6M/39.0M [04:52<00:03, 132kit/s]

./blobtools add --busco full_table_transcripts.tsv /BlobDir_folder

Also, if the organism has no taxid because it's new to science, what can be done besides adding a fake/approximate tax id? Must the taxid be the one of genus and species or could be another rank?

Thanks.

**Comment by rjchallis** [comment]
Thanks for reporting this behaviour. This looks a slight mismatch between what is a valid BlobDir and what I was considering to be valid when I wrote the validator. The validator checks that all required metadata is there and that the various fields are intact for hosting on the public Viewer. As the documentation for `blobtools create` (see [creating-a-dataset](https://blobtoolkit.genomehubs.org/blobtools2/blobtools2-tutorials/creating-a-dataset/)) says, taxid, etc are optional as they are not strictly required for most of BlobToolKit to work.

I'm inclined to think that both definitions of 'valid' are useful so I think that adding a flag to the validator to make it more/less stringent will probably be the best solution here.

The missing taxid when you have used the `--taxid` parameter is an implementation not meeting expectation bug - in that context the taxid is used to add lineage information to the metadata but really should also add/update the taxid and could be used to set the name if no other taxon name is provided. I'll update this to be a bit more user friendly. 

As for adding an approximate taxid, I expect that any rank should be fine, but I haven't tested this. The main function is to add lineage information to help with searching for datasets so it probably isn't too important for the way you are using BlobToolKit.

**Comment by rjchallis** [comment]
added a `--basic` flag as described [here](https://blobtoolkit.genomehubs.org/specification/specification-tutorials/validating-datasets/)
